-- UP
CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  email TEXT
)

CREATE TABLE Article (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  content TEXT,
  ownerId INTEGER REFERENCES User(id)
)

-- Down

DROP TABLE User;
DROP TABLE Article;